"""update field  category and tasks tables in database

Revision ID: 336a2cd47e70
Revises: f495be213e66
Create Date: 2026-09-21 13:37:52.970204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336a2cd47e70'
down_revision: Union[str, Sequence[str], None] = 'f495be213e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTasks', sa.Column('category_id_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tblTasks', 'tblCategory', ['category_id_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblTasks', type_='foreignkey')
    op.drop_column('tblTasks', 'category_id_fk')
    # ### end Alembic commands ###
