"""add the is_profile_completed column in the UserModel table

Revision ID: f495be213e66
Revises: fec3cc3e47da
Create Date: 2026-09-12 10:59:33.825901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f495be213e66'
down_revision: Union[str, Sequence[str], None] = 'fec3cc3e47da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblUsers', sa.Column('is_profile_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblUsers', 'is_profile_completed')
    # ### end Alembic commands ###
