"""alter table and add the column in the tblTasks table and add the is_delete column name

Revision ID: fec3cc3e47da
Revises: 1781bece024c
Create Date: 2026-09-11 19:51:32.402981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec3cc3e47da'
down_revision: Union[str, Sequence[str], None] = '1781bece024c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTasks', sa.Column('is_delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblTasks', 'is_delete')
    # ### end Alembic commands ###
